src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from marketing.sitemaps import PostSitemap,CategorySitemap,FlatPageSitemap
sitemaps = {'categories': CategorySitemap,'posts': PostSitemap,'flatpages': FlatPageSitemap}


urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('contact/', include('contacts.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('newsletter/', include('newsletter.urls' , namespace='newsletter')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('sw.js', (TemplateView.as_view(template_name="sw.js", content_type='application/javascript', )), name='sw.js'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/newsletter/urls.py
from django.urls import path 
from .views  import  newsletter_subscribe

app_name = 'newsletter'

urlpatterns = [
   
    path('subscribe', newsletter_subscribe, name='subscribe'),
    
]

src/newsletter/models.py
from django.db import models

class NewsUsers(models.Model):
	name = models.CharField(max_length = 30)
	email = models.EmailField()
	date_added = models.DateField(auto_now_add=True)

	class Meta:
		verbose_name = "NewsUser"
		verbose_name_plural = "NewsUsers"
	def __str__(self):
		return self.email

src/newsletter/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsUsers

 #creating model forms   
class NewsUserForm(forms.ModelForm):
	class Meta:
		model = NewsUsers
		fields = ['name','email']

src/newsletter/views.py
from django.shortcuts import render
from django.contrib import messages

from .forms import NewsUserForm
from . models import NewsUsers
from .emails import send_multiple_email


def newsletter_subscribe(request):
	if request.method == 'POST':
		form = NewsUserForm(request.POST)
		if form.is_valid():
			instance = form.save(commit=False) #we dont want to save just yet
			if NewsUsers.objects.filter(email=instance.email).exists():
				messages.warning(request, "your Email Already exists in our database")
			else:
				instance.save()
				messages.success(request, "your Email has been submitted to our database")
				send_multiple_email(instance.name, instance.email)
				
	else:
		form = NewsUserForm()

	context = {'form':form}
	template = "newsletter/subscribe.html"
	return render(request, template, context)

src/newsletter/templates/newsletter/email-subscribe.html
<p> <h2>Hello {{name}}</h2> Welcome to the Achieng Cindy Blog Newsletter and much thanks for signing up.</p>
<p>You will find the most exciting and informative news about:</p>

<ul>
    <li> Python</li>
    <li> Django</li>
    <li> Latest Web development tools</li>
    <li> .. and much more</li>
  </ul>

<p> That will go a long way to see you grow</p>

src/newsletter/templates/newsletter/subscribe.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
            <div class="signup-form">
                    <h2>Please Subscribe</h2>
                
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% else %}
                <form action="{% url 'newsletter:subscribe' %}" method="post" class="newsletter-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" value="Send e-mail" id="submit-button">submit</button>
                           
                </form>
                {% endif %}
                </div>

    </div>
</div>


{% endblock %}