.vscode/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    # path('<int:id>/', views.post_edit, name='post_edit'),
    # #re_path(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    # # re_path(r'^search/$', views.post_search, name='post_search'),
    path('<slug:slug>/', views.category_list, name='category_list'),
    path('dynamicimages', views.dynamic_images, name='dynamic_images')
]

.vscode/blog/forms.py
from django import forms
from .models import  Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
       

.vscode/blog/templates/blog/post/category.html
{% extends "base.html" %}
{% load blog_tags %}
{% block title %}{{ category.name }}{% endblock %}
{% block content %}
<div class="container topspace">
        <h2>{{ category.name }}</h2>
        {{ category.description }}
        
        {% endblock %}

</div>

.vscode/blog/templates/blog/post/detail.html
{% extends "base.html" %}
{% load blog_tags %}
{% load staticfiles %}
{% block title %}{{ post.title }}{% endblock %}


{% block content %}
<div class="coontainer topspace">
        <article class="row elements-item-inner">
                <div class="detail-post column col-5">
                    <section class="single-post">
                        <header id="entry-header">
                            <h2>{{ post.title }}</h2>
                            <figure class="">
                                {% include "tags/detail_thumbnail.html" %}
            
            
                                <figcaption class="single-caption text-center">
                                    {% if post.credit %}{{ post.credit|markdown }}{% else%}
                                    <a href="https://achiengcindy.com">Image By Cindy</a>{% endif %}
            
                                </figcaption>
            
                            </figure>
                            <span>published on:
                                <a href="https://achiengcindy.com" rel="bookmark">
                                    <time class="entry-date date" pubdate=''>{{ post.publish }}</time>|
                                    <time class="updated date">{{ post.updated }}</time>
                                </a>
                            </span>
                            by
                            <span class="author vcard"><a class="url fn n"
                                    href="https://achiengcindy.com/aboutcindy/">{{ post.author }}</a></span>
                            <span class="cat-links">
            
            
                                In categor{{ categories.count|pluralize:"y,ies" }}:
                                {% for c in categories %}
                                <a href="{{ c.get_absolute_url }}" rel="category tag">{{ c.title }}</a>
                                {% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </span>
                        </header>
                        <div id="post-excerpt"> {{ post.body|markdown }}
                        </div>
                        <footer id="post-social">
                            <p class="tags">
                                Tags:
                                {% for tag in post.tags.all %}
                                <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                                    {{ tag.name }}
                                </a>
                                {% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </p>
            
            
                            <ul class="social-buttons mb">
                                <li>
                                    <a style="background-color : #f26522;" target="_blank" class='share-email'
                                        href="mailto:?subject={{post.title|urlencode}}&body=http://achiengcindy.com{{post.get_absolute_url|urlencode}}">✉</a>
                                </li>
                                <li>
                                    <a style="background-color : rgb(66, 101, 185)" target="_blank"
                                        href="https://www.facebook.com/sharer/sharer.php?u=http://achiengcindy.com{{post.get_absolute_url|urlencode}}">f</a>
            
                                </li>
                                <li>
                                    <a style="background-color : rgb(85, 172, 238)" target="_blank"
                                        href="https://twitter.com/home?url={{post.get_absolute_url|urlencode}}&text={{post.title|urlencode}}&via=achiengcindy.com"
                                        class="share-twitter">t</a>
                                </li>
                                <li>
                                    <a style="background-color: rgb(76, 174, 227)" target="_blank"
                                        href="http://www.linkedin.com/shareArticle?url=http://achiengcindy.com{{post.get_absolute_url|urlencode}}&title={{post.title|urlencode}}&summary={{title}}&source=achiengcindy.com">
                                        l</a>
                                </li>
            
                            </ul>
                        </footer>
                    </section>
                    <section class="related_posts mb">
                        <h3>Related Articles</h3>
                        <!--https://unicode-table.com/en/sets/emoji/-->
                        <ul class="row">
                            {% for post in similar_posts %}
                            <li class="column col-2 column-3 col-4">
                                <article class="related-article">
                                    {% include 'tags/list_thumbnail.html' %}
                                    <h4 class="related-post-title"><a href="{{post.get_absolute_url}}"
                                            class="article-related-link"></a>
                                        {{post.title}}</h4>
                                </article>
                            </li>
                            {% empty %} No Related post ☹ ,definately Check again soon! {% endfor %}
                        </ul>
                    </section>
            
                    <!-- /.related_posts -->
                    <section class="author-bio mb">
                        <img class="avatar" src="{% static 'images/cindyavartars-100w.webp' %}"
                            srcset="{% static 'images/cindyavartars-90w.jpg' %}" alt="cindy achieng" />
                        <div class="author-description" style="padding-left:6em;">
                            <h3 class="author-name" style="margin-top:0;"><a href="https://achiengcindy.com"
                                    alt="{{ post.author }}">{{ post.author }}</a></h3>
                            <p>I am a mobile-web developer highly skilled in django and Co-founder of Oark Limited a tech company
                                based in Nairobi Kenya.
                                I love to share my coding journey with the world with the aim to teach ,learn and inspire.
                                <a href="/aboutcindy/">More about Cindy</a>
                            </p>
                        </div>
                    </section>
                    <!--.author-bio-->
            
                    <!--     <section class="comments">
                        {% with comments.count as total_comments %}
                        <h3>{{ total_comments }} comment{{ total_comments|pluralize }}</h3>
                        {% endwith %}
            
                        {% for comment in comments %}
            <div class="comment">
            <p class="info">
            Comment {{ forloop.counter }} by {{ comment.commenter }}
            {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
            </div>
            {% empty %}
            <p>There are no comments yet.</p>
            {% endfor %}
            
            {% if new_comment %}
            <h2>Your comment has been added.</h2>{% else %}
            <h2>Add a new comment</h2>
            <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <button type="submit">Post Comment</button>
            </form>
            {% endif %}
                </section> -->
                    <section class="comments-area">
                        <div id="disqus_thread"></div>
                        <script>
                            /**
                             *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                             *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
            
                            var disqus_config = function () {
                                this.page.url = "https://achiengcindy.com/{{post.get_absolute_url}}"; // Replace PAGE_URL with your page's canonical URL variable
                                this.page.identifier = "{{post.id}}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                            };
            
                            (function () { // DON'T EDIT BELOW THIS LINE
                                var d = document,
                                    s = d.createElement('script');
                                s.src = 'https://achiengcindy.disqus.com/embed.js';
                                s.setAttribute('data-timestamp', +new Date());
                                (d.head || d.body).appendChild(s);
                            })();
                        </script>
                        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments
                                powered by Disqus.</a></noscript>
            
                    </section>
                </div>
                <aside class="sidebar column col-6">
                    <h3>Trending <span>🔥</span> Post</h3>
                    {% get_most_commented_posts as most_commented_posts %}
                    <ul>
                        {% for post in most_commented_posts %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </aside>
            </article>
</div>


{% endblock %}

.vscode/blog/templates/blog/post/list.html
{% extends "base.html" %}
{% load blog_tags %}
{% block title %}Blog{% endblock %}
{% block content %}


<section class="topspace masonry  elements-item-inner inner-item">
        
                        {% for post in posts %}
        <article class="brick mb">
                <header id="entry-header">
                        <figure>{% include "tags/list_thumbnail.html" %}</figure>
                        <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                </header>
                <div id="post-excerpt"> {{ post.body|truncatewords:30|markdown }}</div>
                <footer id="post-meta">
                        <div class="post-bottom-left text-left">
                                <div class="category">
                                </div>
                        </div>
                        <div class="post-bottom-right text-right">
                                <a href="{{ post.get_permalink_url }}" class="btn-read-more" rel=canonical> <span
                                                class="edgtf-btn-text">Read More</span> </a>
                        </div>
                </footer>
        </article>
        {% endfor %}
       
</section>
{% include "tags/pagination.html" with page=posts %}
{% endblock %}